# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trdg.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntrdg.proto\x12\x04trdg\"\r\n\x0bTextRequest\"\'\n\x08TextData\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05image\x18\x02 \x01(\x0c\x32\x36\n\x04Trdg\x12.\n\x07GetText\x12\x11.trdg.TextRequest\x1a\x0e.trdg.TextData\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'trdg_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TEXTREQUEST._serialized_start=20
  _TEXTREQUEST._serialized_end=33
  _TEXTDATA._serialized_start=35
  _TEXTDATA._serialized_end=74
  _TRDG._serialized_start=76
  _TRDG._serialized_end=130
# @@protoc_insertion_point(module_scope)
